sudo: false
language: node_js
node_js: stable
cache: npm
branches:
  only:
    - master
script:
  - hexo clean
  - hexo generate

after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git push --quiet --force https://$REPO_TOKEN@github.com/ronhuafeng/ronhuafeng.github.io.git master
