baseURL = "https://blog.formalscience.com/"
languageCode = "zh-cn"
title = "不是追风少年"
theme = "diary"

disqusShortname = "bef0rewind-blog"

[frontmatter]
date = [":filename", ":default"]

[permalinks]
posts = "/:year/:month/:day/:filename"